<a href="https://colab.research.google.com/github/sumitra122/Classification-Models/blob/master/Classification_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# importing dataset
dataset = pd.read_csv('datasets_738_1370_glass.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[[ 1.52101 13.64     4.49    ...  8.75     0.       0.     ]
 [ 1.51761 13.89     3.6     ...  7.83     0.       0.     ]
 [ 1.51618 13.53     3.55    ...  7.78     0.       0.     ]
 ...
 [ 1.52065 14.36     0.      ...  8.44     1.64     0.     ]
 [ 1.51651 14.38     0.      ...  8.48     1.57     0.     ]
 [ 1.51711 14.23     0.      ...  8.62     1.67     0.     ]]


In [ ]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [ ]:
#Splitting the dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [ ]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[-0.57016436 -0.8021311   0.59394972 ... -0.73204433 -0.36042422
  -0.5574741 ]
 [-0.12738242 -0.01596892  0.14178098 ...  0.03745343 -0.36042422
  -0.5574741 ]
 [ 1.00931153 -0.48275272  0.68438347 ...  0.59585004 -0.36042422
   1.35466909]
 ...
 [-0.4578167   0.34026082  0.70525279 ... -0.74566376 -0.36042422
  -0.5574741 ]
 [ 2.7110481   0.67192299  0.71916568 ...  0.57542089 -0.36042422
   0.56731601]
 [-1.73659739 -0.54417164 -1.85471789 ... -1.39258666 -0.36042422
  -0.5574741 ]]


In [ ]:
print(x_test)

[[-3.95034190e-01  1.54407167e+00 -1.85471789e+00  1.75197496e+00
   8.54487173e-01 -6.88607851e-01 -1.70242868e-02  1.01064199e+00
  -5.57474100e-01]
 [-1.63730189e-01 -8.63550025e-01  5.66123950e-01 -1.61246920e-01
   4.37862630e-01  1.79249921e-01 -2.00886585e-01 -3.60424223e-01
  -5.57474100e-01]
 [-6.82512019e-01 -1.09694192e+00  5.66123950e-01  8.43677703e-01
   7.89389588e-01  1.65689643e-01 -6.09469468e-01 -3.60424223e-01
   4.54837002e-01]
 [ 1.93138841e-01  6.84206777e-01 -1.92128234e-01  2.44588024e-01
  -3.30288871e-01 -6.88607851e-01  4.05178026e-01 -3.60424223e-01
  -5.57474100e-01]
 [ 1.72635393e+00 -3.68513524e-03 -1.85471789e+00  2.83238971e-01
  -5.25581625e-01 -2.54678965e-01  2.22337186e+00 -3.60424223e-01
  -5.57474100e-01]
 [-8.47729162e-01 -5.19604069e-01  6.35688371e-01  1.47960657e-01
   6.46174901e-01  2.47051309e-01 -6.91186045e-01 -3.60424223e-01
  -5.57474100e-01]
 [-1.83391029e-02 -5.19604069e-01  6.63514139e-01 -7.21685652e-01
  -3.69347422e-01  1.7924992

In [ ]:
#Training the dataset into train set in Logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#predicting test result
y_pred = classifier.predict(x_test)

In [ ]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  3  0  0  0  0]
 [10 12  0  1  1  0]
 [ 3  2  0  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  0  0  7]]


0.5925925925925926

In [ ]:
#Training the dataset into train set in K-NN
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
#predicting test result
y_pred = classifier.predict(x_test)

In [ ]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 9  5  0  0  0  0]
 [ 8 15  0  1  0  0]
 [ 3  2  0  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  0  0  7]]


0.6111111111111112

In [ ]:
#Training the dataset into train set in svm linear kernel
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
#predicting test result
y_pred = classifier.predict(x_test)

In [ ]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[10  4  0  0  0  0]
 [ 9 14  0  1  0  0]
 [ 3  2  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  7]]


0.6111111111111112

In [ ]:
#Training the dataset into train set in Guassian rbf classifier
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
#predicting test result
y_pred = classifier.predict(x_test)

In [ ]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[10  4  0  0  0  0]
 [ 6 18  0  0  0  0]
 [ 2  3  0  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  0  0  7]]


0.7037037037037037

In [ ]:
#Training the dataset into train set in svm polynomial classification
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', random_state = 0)
classifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
#predicting test result
y_pred = classifier.predict(x_test)

In [ ]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14  0  0  0  0  0]
 [19  3  0  1  1  0]
 [ 4  1  0  0  0  0]
 [ 1  1  0  0  0  0]
 [ 2  0  0  0  0  0]
 [ 0  0  0  0  0  7]]


0.4444444444444444

In [ ]:
#Training the dataset into train set in svm sigmoid classification
from sklearn.svm import SVC
classifier = SVC(kernel = 'sigmoid', random_state = 0)
classifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
#predicting test result
y_pred = classifier.predict(x_test)

In [ ]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  3  0  0  0  0]
 [19  4  0  1  0  0]
 [ 3  2  0  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  0  0  7]]


0.4444444444444444

In [ ]:
#Training the dataset into train set in Decision Tree classification
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [ ]:
#predicting test result
y_pred = classifier.predict(x_test)

In [ ]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 9  4  1  0  0  0]
 [ 5 17  1  0  1  0]
 [ 1  2  2  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  1  1]
 [ 0  0  0  0  0  7]]


0.7037037037037037

In [ ]:
#Training the dataset into train set in Random forest classification
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
#predicting test result
y_pred = classifier.predict(x_test)

In [ ]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[12  2  0  0  0  0]
 [ 7 16  1  0  0  0]
 [ 3  1  1  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  7]]


0.7407407407407407